[package]
id = venn_diagram_viz_for_dashboard_studio

[id]
version = 0.1.0
name = venn_diagram_viz_for_dashboard_studio

[ui]
is_visible = 1
label = Venn Diagram Viz For Dashboard Studio
show_in_nav = 0

[launcher]
author = Daniel Spavin
description = A custom visualization for Splunk Dashboard Studio
version = 0.1.0

[install]
is_configured = 0
build = <@- buildNumber @>
check_for_updates = 0

[manifest]
category = Custom
